### ISSUE TITLE
Why those sync functions  can just use random strategy?

### ISSUE THREAD

**Issue by WanliTian** [helpshift/ekaf#21]
Is there any special reasons?

**Comment by WanliTian** [comment]
And ekaf dont support hash. How can i keep the order of messages with cuid.

**Comment by bosky101** [comment]
Hi

You can change the partition strategy to be one of 3

# Random strategy 
Fastest, can go to any partition
No check for balancing load across partitions

# strict round robin (recommended)
1st message goes to 1st partition
2nd message to 2nd partition
Nth message goes to Nth partition
Again N+1 message goes to 1st partition, etc

We currently send 300+ million events per day using kafboy/ekaf:produce_aync_batched/2 using 7-14 (autoscale) servers and IIRC 5 partitions. Load is evenly distributed all available partitions. You can easily add metrics to graph this. (See ekaf_demo.erl)

Are you asking to make strict round robin the default strategy?

And yes - there is no hashing or custom partitioner yet. Will add that by v2.0.0
Are you more interested in a specific hashing function ? Or is to shard based on some user id ?

~B

**Comment by WanliTian** [comment]
I want to use produce_sync, not producer_async.

If shard is provided, that's perfect....
But I just see a `todo`  from the source code.

**Comment by bosky101** [comment]
you can use product_sync also. partition strategy will affect sync and async.

custom partition picker has been requested by several folks recently, will work on it this weekend.

**Comment by WanliTian** [comment]
That's perfect~~~
Full of expectation

**Comment by bosky101** [comment]
Just saw your work on your fork, does that work? Glad to see you deep dive
into the code.

~B

**Comment by WanliTian** [comment]
It works.
It's ugly.
