### ISSUE TITLE
application:set_env results in undef error

### ISSUE THREAD

**Issue by harekumar** [helpshift/ekaf#22]
Hi

I am trying to set env variable as mentioned in readme doc. For reference adding the code. 
application:load(ekaf).
application:set_env(ekaf, {ekaf_bootstrap_broker,{Server,Port}}).

But doing that results in undef 

error: undef
[{application,set_env,
              [ekaf,{ekaf_bootstrap_broker,{"localhost",<<"9092">>}}],
              []},

Can anyone please suggest what changes are required to get it working?

**Comment by bosky101** [comment]
Pass 3 arguments to set env

Try 

    application:set_env(ekaf, ekaf_bootstrap_broker, {"localhost",<<"9092">>})

~B

**Comment by harekumar** [comment]
Thanks. That solved the issue. 

But got another one when producing to some topic. And I guess, It is producing that error because of the above change. Can u please suggest? 
ekaf:produce_sync(Topic, <<"foo">>).
** exception exit: {{function_clause,
                        [{inet_tcp,getserv,
                             [<<"9092">>],
                             [{file,"inet_tcp.erl"},{line,35}]},
                         {gen_tcp,connect1,4,[{file,"gen_tcp.erl"},{line,154}]},
                         {gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},
                         {ekaf_server,downtime,2,
                             [{file,"src/ekaf_server.erl"},{line,94}]},
                         {gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,503}]},
                         {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,237}]}]},
                    {gen_fsm,sync_send_event,[<0.9812.51>,prepare]}}
     in function  gen_fsm:sync_send_event/2 (gen_fsm.erl, line 208)
     in call from ekaf_lib:prepare/2 (src/ekaf_lib.erl, line 51)
     in call from ekaf_lib:common_sync/4 (src/ekaf_lib.erl, line 81)

**Comment by harekumar** [comment]
Never mind. It's solved. 

Port number is expected as number/Integer in inet_tcp.erl
