### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by WanliTian** [helpshift/ekaf#26]
it's better to add the project name for registering process name when using `gproc`, like this:

    gproc:reg({n,l,{ProjectName, TopicName}}).

**Comment by bosky101** [comment]
This will also make sense for the pg2 group created. currently it is <topicname>, but prefixing with ekaf.topicname will be better.

thanks, will update here when done.

**Comment by bosky101** [comment]
Fixed in c2246f2c4f63c6e78e21afbeb17c66558ad12774 

gproc & pg2 topics are now prefixed with `<<"ekaf.", Topic/binary>>`
