### ISSUE TITLE
Kafka reports: too many connections when using ekaf

### ISSUE THREAD

**Issue by WanliTian** [helpshift/ekaf#27]
What can make ekaf_fsm process's mailbox including too many "reconnect" messages?
This happens to me.
and my kafka cluster report: too many connections

**Comment by bosky101** [comment]
which sha are you using?

**Comment by bosky101** [comment]
is this related https://github.com/ericliang/ekaf/commit/2b2082e0c4a9464cdea39772a18db9f1bb15bdfc

**Comment by WanliTian** [comment]
i use custom partition strategy.  dose it work well?

**Comment by bosky101** [comment]
the reconnect issue was reported by layer; but it is clear that the brokers
were unavailable for a while.

custom partition strategy has no change on this behaviour.

**Comment by WanliTian** [comment]
thx so much. 
i will have a try.
