### ISSUE TITLE
Some questions for custom partition strategy

### ISSUE THREAD

**Issue by WanliTian** [helpshift/ekaf#30]
i found that the custom partition strategy is ineffective, and sometimes it's not a strict custom policy. i think people always want a strict hash policy when they use it.
the code here:
https://github.com/helpshift/ekaf/blob/master/src/ekaf_server.erl#L360
i think it's better to return an error code than a wrong process

in my situation, there are so many partitions. if processes are ask to determine a specified partition, it's really ineffective. why not just use gproc to regist a name for that process, like this:
    gproc:reg({n,l,{Topic, Partition}}).

i think there are no need multiple processes for one partition when using custom partition strategy. But it you want, you can like this:
    gproc:reg({p, l, {Topic, Partition}})
    Pids = gproc:lookup_pids({p,l,{Topic,Partitions}})

**Comment by bosky101** [comment]
A worker has a fixed partition. Partition Picker decides which partition to pick. Which in turns now decides among all workers for this partition, which worker to pick? Once a worker is picked for partition P, the next call picks another worker for partition P. it picks workers for the same partition in round robin.
 
    ekaf:produce_async_batched(<<"topic">>, {<<"user1">>,<<"foobar">>}).
    ekaf:produce_sync(<<"topic">>, [{<<"user1">>, <<"foo">>},  {<<"user2">>, <<"bar">>}]).

So i would have to create `gproc:reg({n,l,{Topic, <<"foo">>})`,  `gproc:reg({n,l,{Topic, <<"bar">>})`
This is not scalable.

See https://github.com/helpshift/ekaf/commit/b3a29143d5a82247c458b9fc502a282cb5702dc5 for more. 

Another example. Consider 2 Partitions and 2 workers each.
    ekaf:produce_async_batched(<<"topic">>, {<<"user1">>,<<"foobar">>}).
    %% goes to P1 worker1
   
    ekaf:produce_async_batched(<<"topic">>, {<<"user1">>,<<"foobar">>}).
    %% goes to P1 worker2
    
    ekaf:produce_async_batched(<<"topic">>, {<<"user1">>,<<"foobar">>}). 
    %% goes to P1 worker1

So to conclude, `Topic` alone cannot determine which partition that message should be routed to. It depends on the `Key`.

**Comment by bosky101** [comment]
Can you give more details on the wrong process being returned. That should not happen. Because `you` are writing the function that decides if a worker should go to a partition. I hope you have set

    % to always route messages with keys to the same partition
    {ekaf_callback_custom_partition_picker, {your_module, 
                                             your_custom_partition_picker}}

**Comment by WanliTian** [comment]
my english is too pool and i think you have not got my meaning.

what i have say is that:

pick_first_matching([], _, DefaultWorker)->
    DefaultWorker;
pick_first_matching([Worker|Workers], Pred, DefaultWorker)->
    case (catch Pred(Worker)) of
        true ->
            Worker;
        false ->
            pick_first_matching(Workers, Pred, DefaultWorker);
        _ ->
            DefaultWorker
    end.

using this code, we should iterate all the gen_fsm processes to choose one process with the right partition.
it's better to  add {partition, pid} to one hash tree,

**Comment by WanliTian** [comment]
and we can use gproc to achieve that.

**Comment by bosky101** [comment]
Does gproc do round-robin of all matching pid's?

**Comment by bosky101** [comment]
Also even when using custom - having just 1 worker for a partition will lead to large message inbox's, and possibly other memory & performance issues in my opinion.

**Comment by WanliTian** [comment]
no, just for custom partition strategy

**Comment by bosky101** [comment]
if you choose 1 worker per partition for that topic, then the list will contain only 1 worker. If you want - can have a special case of picking 1 worker via gproc if the worker count = 1.

**Comment by WanliTian** [comment]
%%for gen_fsm process
     gproc:reg({p,l,{Topic,Partition}})

    %%when picker
     Partition = Key % Count,
     List = gproc:lookup_pids({p,l,{Topic, Partition}})
     Pid = lists:nth(List, random:uniform(length(List)))

i know what you mean.
see this code.
