### ISSUE TITLE
Partitioning strategy working with Kafka 0.10.0?

### ISSUE THREAD

**Issue by dennis-qian** [helpshift/ekaf#43]
I tried to use different built-in partitioning strategy by setting "ekaf_partition_strategy" as ekaf's application environment variable in my app. But no strategy worked as expected. I also tried to set them via config file but that didn't help either. The end result is inconsistent distribution of messages onto partitions without any pattern. Most of the time ekaf does not write to all partitions but just some of them.

**Comment by bosky101** [comment]
Paste the part where you configure the partitions please.

~B
