### ISSUE TITLE
ekaf app not restart when 6 erl node restart in turn

### ISSUE THREAD

**Issue by lcwxz1989** [helpshift/ekaf#49]
I have 6 node online,I want to update kafka from 8 to 10.2.So I change the configure for ekaf,but ekaf didi not produce to new kafka broker. And then I add log to ekaf_server mode generic_init function to get the topic and broker info. But I get nothing,so I know the ekaf application didi not restart.But why

**Comment by bosky101** [comment]
See if you have made all the settings as done in https://github.com/helpshift/ekaf/blob/master/test/ekaf_tests.erl#L64

Also set metrics callbacks for debugging as done in https://github.com/helpshift/ekaf/blob/master/src/ekaf_demo.erl#L46

~B
