### ISSUE TITLE
Tunable partition choosing strategy?

### ISSUE THREAD

**Issue by qrilka** [helpshift/ekaf#5]
What about adding support to something like https://github.com/mumrah/kafka-python/blob/master/kafka/partitioner/base.py to ekaf?
Actually I want to have "constant" partitioner, i.e. send events to the same partition from 1 server like in the example here http://blog.cloudera.com/blog/2014/09/apache-kafka-for-beginners/
Is it possible with ekaf? I couldn't find a way how to do that

**Comment by vglukhovskiy** [comment]
Any progress please on this ticket please?
We really need to have ability to control partitions.  Any option would suffice.
Thanks

**Comment by RomanShestakov** [comment]
+1 - would be really really useful function, any plans to implement any time soon?

**Comment by bosky101** [comment]
Will add by November

**Comment by Gatzy118** [comment]
+1 Will be really useful!

**Comment by RomanShestakov** [comment]
hi Bhasker - any progress with this ticket so far?

**Comment by thatJoeGuy16** [comment]
this would be a great feature, what kind of eta are we looking at?

**Comment by jccampagne** [comment]
+1 - following thread/issue, this is something that would be very useful.
Thanks for the update and effort.
Looking forward to use this feature.

**Comment by bosky101** [comment]
Sorry for the delay, i'm done with my internal deadlines - will fix it this weekend.

Plan of action:
1.  Expose current partitions, workers for a topic
2.  If partition strategy is custom, then add a new app env that will call M:F/5 before picking a worker.
3.  M:F/5 will be passed a dictionary of `[{Topic, WorkerPids},...]` and a `CallbackPid`
4.  You must message pass `{ok, PickedWorker}` back to the `CallbackPid` (if the partition is down, that way you can still pick another partition/worker and pass to the callbackpid) or `undefined`

**Comment by RomanShestakov** [comment]
this is awesome, thanks a lot for update Bhasker! Really looking forward to it

**Comment by vglukhovskiy** [comment]
Great!  Looking forward.

**Comment by bosky101** [comment]
@qrilka @mitchellwrosen @vglukhovskiy @RomanShestakov @Gatzy118 @jccampagne @thatJoeGuy16 Please test https://github.com/helpshift/ekaf/tree/feature/custom-partition-strategy out and let me know. Will merge into master when i have time to write tests.

**Comment by vglukhovskiy** [comment]
AWESOME!  Will try tomorrow. 
Many thanks

**Comment by RomanShestakov** [comment]
thank you very much - will check shortly!

**Comment by vglukhovskiy** [comment]
@bosky101,
We did manage to use your solution with a basic custom partition picker.
Many thanks one more time.

**Comment by RomanShestakov** [comment]
it works as advertised - many thanks for quick turnaround

**Comment by jccampagne** [comment]
@bosky101 thanks for the patch
